### ISSUE TITLE
menuSelectedClass is not updated

### ISSUE THREAD

**Issue by cycle4passion** [bagusindrayana/scrollpage-js#2]
Clicking on a menu item does give it the appropriate "active" class, but the class is not updated on a scrollpage event. Also active class for 1st menu items should be added on initialization rather than requiring hardcoded. Thanks for a small and great project.

**Comment by bagusindrayana** [comment]
thanks for the advice & report i will fix it soon in the next update

**Comment by bagusindrayana** [comment]
I have updated the latest version with improvements and some additions, I may not have done a thorough checking and testing, thank you for the response.

**Comment by cycle4passion** [comment]
Looks great to me, you beat me to it. 

If you are interested, here is a more complex sidenav example using mouseover tooltip. Feel free to codepen fork and use for your site. Thanks again

[Codepen](https://codepen.io/c4p/pen/RwjYEaq)
